steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/myapp:v1', '.']
  timeout: 180s

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/myapp:v1']

- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --image=gcr.io/$PROJECT_ID/myapp:v1
  - --location=us-central1-c
  - --cluster=hello-java-cluster